SP2
nvbach91/4IZ268-2018-2019-ZS pull request #346
Opened 2019-01-08 11:36 UTC by PavelDvoriak

Ahoj, na základě mailu vytvářim PR. Zatím toho zas tolik není a v tom kódu je celkem nepořádek...

2019-01-08 12:15 UTC, nvbach91 commented
@PavelDvoriak blizi se termin, stihnes to za 3 dny? takhle mi nedavas moc prostoru k revizi, to nemusi vest k dobremu vysledku

2019-01-08 12:18 UTC, nvbach91 requested changes

2019-01-08 12:18 UTC, nvbach91 commented on www/dvop06/trip_planner/css/main.css
> +    font-family: roboto;
Roboto

2019-01-08 12:18 UTC, nvbach91 commented on www/dvop06/trip_planner/css/main.css
> +       #map {
naformatovat kod

2019-01-08 12:18 UTC, nvbach91 commented on www/dvop06/trip_planner/css/main.css
> +        font-family: Roboto;
font uz je v body

2019-01-08 12:18 UTC, nvbach91 commented on www/dvop06/trip_planner/js/main.js
> +                content: '<div contentEditable="true">Write your note here :)</div>'
doufam ze sem prijdou obrazky a dalsi uzitecne informace

2019-01-08 12:18 UTC, PavelDvoriak commented
Takhle, pozdější termín bych bral 100% (mám na pátek i test z webů), ale další už nebyl volnej.

2019-01-10 20:06 UTC, PavelDvoriak commented
@nvbach91 update: Zatím jsem s tím moc nepohnul, snažil jsem se nějak pracovat s tím Drive API, ale nešlo to. Od posledně tam je vlastně navíc jen ukládání a načítání z localStorage

2019-01-10 22:50 UTC, nvbach91 requested changes
@PavelDvoriak neprisel jsem na to jak se aplikace pouziva
cely co vidim je toto
![image](https://user-images.githubusercontent.com/20724910/51002098-87a81b00-1532-11e9-9232-a1a09ce203ec.png)
asi je to kvuli spatnemu pouziti relativnich cest k souborum

2019-01-23 20:46 UTC, PavelDvoriak commented
@nvbach91 Zdravím, práci jsem předělal víceméně od začátku, trochu jsem to zjednodušil. Prosím o feedback, abych to mohl kdyžtak ještě implementovat.

2019-01-24 15:45 UTC, nvbach91 commented
@PavelDvoriak no vida, uz to zacina vypadat k svetu
nedostatky:
- inline js
- poradi script tagu
- html meta
- interaktiviva elementu (hover, cursor, disabled, ...)
- k cemu je LocalStore? hazi to errory, ... nestacilo to dat rovnou do localStorage objektu? (this.storage is undefined)
- zneuziti refreshTripPlaces pri odebirani bodu - to generujes cely seznam odznova, nestaci odebrat jen ten jeden point?

pozadavky:
- info o prihlasenem uzivateli
- nastylovat button v bubline
- pridat do bublinek obrazky k tem points of interest
- pridat filtr pro typy points of interest

2019-01-25 19:59 UTC, nvbach91 commented
@PavelDvoriak prosim commit a push zmen z obhajoby

2019-01-26 14:41 UTC, PavelDvoriak commented
@nvbach91 Je to pushed, prosim o merge

2019-01-26 14:45 UTC, nvbach91 requested changes

2019-01-26 14:45 UTC, nvbach91 commented on www/dvop06/trip_planner/index.html
>  			<div id="CleanMap"><button id="btnCleanMap" onclick="removePlacesMarkers()">Clean Map</button></div>
na tohle jsem zapomnel, jedna se o inline javascript, snahou je oddelit js od html... vsechny elementy s udalosti je potreba vybrat v javascriptu a tam ty eventy nabindovat, takze napr. 
```html
<button id="btnCleanMap" onclick="removePlacesMarkers()">Clean Map</button>
```
bude 
```html
<button id="btnCleanMap">Clean Map</button>
```
```js
$('#btnCleanMap').click(removePlacesMarkers);
```
prosim o update

2019-01-30 14:24 UTC, nvbach91 commented
@PavelDvoriak bues to jeste opravovat?

2024-02-02 18:41 UTC, closed without merging